name: Install and run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    # - name: Set up Python 3.12
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: "3.12"
    - name: Install dependencies and run tests
      run: make tests
